---
- name: Curl Download the cert
  hosts: all

  tasks:

    - name: folder
      ansible.builtin.file:
        path: /home/ansible/variable/
        state: directory

    - name: curl 
      ansible.builtin.get_url:
        url: "{{ cert_url }}"
        dest: /home/ansible/variable/



