---
- name: Curl Download the cert
  hosts: all
  become: true

  tasks:

    - name: curl 
      ansible.builtin.get_url:
        url: https://curl.se/docs/caextract.html/cacert.pem
        dest: /home/ec2-user/cacert.pem

