---
- name: Curl Download the cert
  hosts: all

  tasks:

    - name: folder
      ansible.builtin.file:
        path: /home/ansible/mozilla/
        state: directory

    - name: curl 
      ansible.builtin.get_url:
        url: https://curl.se/ca/cacert.pem
        dest: /home/ansible/mozilla/cacert.pem



